#!/bin/bash

if [ -z "$1" ]; then
  echo "Example usage: $0 <context>"
  echo "Available contexts: cli, wasm"
  exit 0
fi

if [[ "$1" == "cli" ]]; then
  cargo build --release --bin cli
fi

if [[ "$1" == "wasm" ]]; then
  cd wasm_wrapper || exit
  wasm-pack build --target web
  cd ..
fi
