set -g status-style "bg=#193ab7,fg=#eff6ff"
set -g status-left " #[fg=#ffc91d,bg=#193ab7,bold]#S#[nobold] "
set -g window-status-format "#[fg=#eff6ff,bg=#193ab7,bold] #I #W#[nobold] "
set -g window-status-current-format "#[fg=#162455,bg=#ffc91d,bold,dim] #I #W#[nobold,nodim] "
set -g status-right "#[fg=#ffc91d,bg=#193ab7]#(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null) #(git -C #{pane_current_path} rev-parse --git-dir > /dev/null 2>&1 && (git -C #{pane_current_path} status --porcelain | grep -q . && echo '*' || echo 'o')) "
