log_level = "off"
enable_esc_key = true

[modules]
left = ["SystemInfo", "Updates"]
center = ["Workspaces", "WindowTitle"]
right = ["Clock", "Settings"]

[updates]
check_cmd = "checkupdates; yay -Qua"
update_cmd = 'foot -e bash -c "yay; echo Done - Press enter to exit; read" &'

[appearance]
font_name = "NotoSansM Nerd Font Mono"
text_color = "{{ primary_50 }}"

[appearance.success_color]
base = "#05df72"
text = "#032e15"

[appearance.primary_color]
base = "{{ opposite_400 }}"
text = "{{ opposite_500_foreground }}"

[appearance.danger_color]
base = "#ff6266"
text = "#440607"

[appearance.background_color]
base = "{{ primary_900 }}"
text = "{{ primary_50 }}"

[appearance.secondary_color]
base = "{{ secondary_400 }}"
text = "{{ secondary_500_foreground }}"
