# -*- conf -*-
# For documentation on these options, see `man fnott.ini`

# Global values
# output=<undefined>#
# min-width=0
max-width=480
max-height=360
# stacking-order=bottom-up
# anchor=top-right
# edge-margin-vertical=10
# edge-margin-horizontal=10
# notification-margin=10
# icon-theme=hicolor
# max-icon-size=32
# selection-helper=dmenu
# selection-helper-uses-null-separator=no
# play-sound=aplay ${filename}

# Default values, may be overridden in 'urgency' specific sections
# layer=top
background={{ primary_900 | no_hashtag }}ff

border-color={{ primary_500 | no_hashtag }}ff
# border-radius=0
border-size=2

# padding-vertical=20
# padding-horizontal=20

dpi-aware=no

title-font=NotoSansM Nerd Font Mono:size=16:fontfeatures=-calt:weight=bold
title-color={{ primary_100 | no_hashtag }}ff
title-format=%a%A

summary-font=NotoSansM Nerd Font Mono:size=14:fontfeatures=-calt:weight=bold
summary-color={{ primary_50 | no_hashtag }}ff
summary-format=%s

body-font=NotoSansM Nerd Font Mono:size=12:fontfeatures=-calt:weight=bold
body-color={{ primary_200 | no_hashtag }}ff
body-format=%b

# progress-bar-height=20
# progress-color=ffffffff
# progress-style=bar

# sound-file=
# icon=

# Timeout values are in seconds. 0 to disable
# max-timeout=0
# default-timeout=0
# idle-timeout=0

[low]
background={{ primary_950 | no_hashtag }}ff
title-color={{ primary_200 | no_hashtag }}ff
summary-color={{ primary_100 | no_hashtag }}ff
body-color={{ primary_300 | no_hashtag }}ff

# [normal]

[critical]
background=ff6266ff
border-color=9d0410ff
title-color=440607ff
summary-color=440607ff
body-color=440607ff
