# -*- conf -*-
# For documentation on these options, see `man fnott.ini`

# Global values
# output=<undefined>#
# min-width=0
max-width=480
max-height=360
# stacking-order=bottom-up
# anchor=top-right
# edge-margin-vertical=10
# edge-margin-horizontal=10
# notification-margin=10
# icon-theme=hicolor
# max-icon-size=32
# selection-helper=dmenu
# selection-helper-uses-null-separator=no
# play-sound=aplay ${filename}

# Default values, may be overridden in 'urgency' specific sections
# layer=top

# border-radius=0
border-size=2

# padding-vertical=20
# padding-horizontal=20

dpi-aware=no

title-font=NotoSansM Nerd Font Mono:size=16:fontfeatures=-calt:weight=bold
title-format=%a%A

summary-font=NotoSansM Nerd Font Mono:size=14:fontfeatures=-calt:weight=bold
summary-format=%s

body-font=NotoSansM Nerd Font Mono:size=12:fontfeatures=-calt:weight=bold
body-format=%b

# progress-bar-height=20
# progress-color=ffffffff
# progress-style=bar

# sound-file=
# icon=

# Timeout values are in seconds. 0 to disable
# max-timeout=0
# default-timeout=0
# idle-timeout=0

[low]
background={{ primary.w950.bg | no_hashtag }}ff
border-color={{ primary.w500.bg | no_hashtag }}ff
title-color={{ primary.w200.bg | no_hashtag }}ff
summary-color={{ primary.w100.bg | no_hashtag }}ff
body-color={{ primary.w300.bg | no_hashtag }}ff

[normal]
background={{ primary.w950.bg | no_hashtag }}ff
border-color={{ primary.w500.bg | no_hashtag }}ff
title-color={{ opposite.w400.bg | no_hashtag }}ff
summary-color={{ secondary.w400.bg | no_hashtag }}ff
body-color={{ primary.w200.bg | no_hashtag }}ff

[critical]
background=ff6266ff
border-color=9d0410ff
title-color=440607ff
summary-color=440607ff
body-color=440607ff
