general {
    col.active_border = rgb({{ primary.w500.bg | no_hashtag }})
    col.inactive_border = rgb({{ primary.w950.bg | no_hashtag }})
}

misc {
    background_color = 0x{{ primary.w950.bg | no_hashtag }}
}
