set -g status-style "bg={{ primary_800 }},fg={{ primary_50 }}"
set -g status-left " #[bg={{ primary_800 }},fg={{ opposite_100 }},bold]#S#[nobold] "
set -g window-status-format "#[bg={{ primary_800 }},fg={{ primary_50 }},bold] #I #W#[nobold] "
set -g window-status-current-format "#[bg={{ opposite_500 }},fg={{ opposite_500_foreground }},bold,dim] #I #W#[nobold,nodim] "
set -g status-right "#[bg={{ primary_800 }},fg={{ primary_50 }}]#(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null) #(git -C #{pane_current_path} rev-parse --git-dir > /dev/null 2>&1 && (git -C #{pane_current_path} status --porcelain | grep -q . && echo '*' || echo 'o')) "
