set -g status-style "bg={{ primary.w800.bg }},fg={{ primary.w800.fg }}"
set -g status-left "#[bg={{ primary.w800.bg }},fg={{ opposite.w200.bg }},bold] #S# [nobold]"
set -g window-status-format "#[bg={{ primary.w800.bg }},fg={{ primary.w800.fg }},bold] #I #W#[nobold] "
set -g window-status-current-format "#[bg={{ opposite.w500.bg }},fg={{ opposite.w500.fg }},bold,dim] #I #W#[nobold,nodim] "
set -g status-right "#[bg={{ primary.w800.bg }},fg={{ opposite.w200.bg }}] #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null) #(git -C #{pane_current_path} rev-parse --git-dir > /dev/null 2>&1 && (git -C #{pane_current_path} status --porcelain | grep -q . && echo '*' || echo 'o')) "
